// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIn9c2-ulQSL5yoG8NoHoEvZPgj84FDAM',
    appId: '1:1066085424652:web:dcde96b298379cb5e9d829',
    messagingSenderId: '1066085424652',
    projectId: 'chat-appp-f5d18',
    authDomain: 'chat-appp-f5d18.firebaseapp.com',
    storageBucket: 'chat-appp-f5d18.firebasestorage.app',
    measurementId: 'G-LP1THY5Y73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfMzG1GYZupqJsNZ8DoOKJkZgL7HTgtI',
    appId: '1:1066085424652:android:254890c27804880ee9d829',
    messagingSenderId: '1066085424652',
    projectId: 'chat-appp-f5d18',
    storageBucket: 'chat-appp-f5d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFHXaXuJiSTJBv6FOn7Fuvhpe4jC09eb8',
    appId: '1:1066085424652:ios:6239e72bcf9fd947e9d829',
    messagingSenderId: '1066085424652',
    projectId: 'chat-appp-f5d18',
    storageBucket: 'chat-appp-f5d18.firebasestorage.app',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFHXaXuJiSTJBv6FOn7Fuvhpe4jC09eb8',
    appId: '1:1066085424652:ios:6239e72bcf9fd947e9d829',
    messagingSenderId: '1066085424652',
    projectId: 'chat-appp-f5d18',
    storageBucket: 'chat-appp-f5d18.firebasestorage.app',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIn9c2-ulQSL5yoG8NoHoEvZPgj84FDAM',
    appId: '1:1066085424652:web:598d1709fdcf1364e9d829',
    messagingSenderId: '1066085424652',
    projectId: 'chat-appp-f5d18',
    authDomain: 'chat-appp-f5d18.firebaseapp.com',
    storageBucket: 'chat-appp-f5d18.firebasestorage.app',
    measurementId: 'G-MF7Y3S0ZTZ',
  );

}